
export const CHECK_LOGIN = "CHECK_LOGIN";
export const SIGN_IN_AUTH = "SIGN_IN_AUTH";


  //PRODUCT ACTION
export const  CREATE_PRODUCT_ACTION = "CREATE_PRODUCT_ACTION"
export const  UPDATE_PRODUCT_ACTION = "UPDATE_PRODUCT_ACTION"
export const  DELETE_PRODUCT_ACTION= "DELETE_PRODUCT_ACTION"
export const  GET_ALL_PRODUCT_ACTION= "GET_ALL_PRODUCT_ACTION"
export const  GET_SPECIFIED_PRODUCT_ACTION= "GET_SPECIFIED_PRODUCT_ACTION"

export const HANDLE_SEARCH_PINPUT  = "HANDLE_SEARCH_PINPUT"


//SUPPLIER ACTIONS
//SUPLIER CONTACTS CRUD
export const  ADD_SUPPLIER_CONTACT_ERROR = "ADD_SUPPLIER_CONTACT_ERROR"
export const  ADD_SUPPLIER_CONTACT_LOADING = "ADD_SUPPLIER_CONTACT_LOADING"
export const  ADD_SUPPLIER_CONTACT_SUCCESS = "ADD_SUPPLIER_CONTACT_SUCCESS"

export const  DELETE_SUPPLIER_CONTACT_ERROR = "DELETE_SUPPLIER_CONTACT_ERROR"
export const  DELETE_SUPPLIER_CONTACT_LOADING = "DELETE_SUPPLIER_CONTACT_LOADING"
export const  DELETE_SUPPLIER_CONTACT_SUCCESS = "DELETE_SUPPLIER_CONTACT_SUCCESS"

export const  EDIT_SUPPLIER_CONTACT_ERROR = "EDIT_SUPPLIER_CONTACT_ERROR"
export const  EDIT_SUPPLIER_CONTACT_LOADING = "EDIT_SUPPLIER_CONTACT_LOADING"
export const  EDIT_SUPPLIER_CONTACT_SUCCESS = "EDIT_SUPPLIER_CONTACT_SUCCESS"

export const  FETCH_SUPPLIER_CONTACT_ERROR = "FETCH_SUPPLIER_CONTACT_ERROR"
export const  FETCH_SUPPLIER_CONTACT_LOADING = "FETCH_SUPPLIER_CONTACT_LOADING"
export const  FETCH_SUPPLIER_CONTACT_SUCCESS = "FETCH_SUPPLIER_CONTACT_SUCCESS"




export const  ADD_SUPPLIER = "ADD_SUPPLIER"
export const  ADD_SUPPLIER_DELIVERY_LOCATION = "ADD_SUPPLIER_DELIVERY_LOCATION"
export const  ADD_SUPPLIER_CATEGORY = "ADD_SUPPLIER_CATEGORY"
export const  ADD_SUPPLIER_REASON = "ADD_SUPPLIER_REASON"


export const  CREATE_SUPPLIER_ADDRESS = "CREATE_SUPPLIER_ADDRESS"
export const  GET_ALL_SUPPLIER_ADDRESS = "GET_ALL_SUPPLIER_ADDRESS"
export const  GET_SPECIFIED_SUPPLIER_ADDRESS = "GET_SPECIFIED_SUPPLIER_ADDRESS"
export const  UPDATE_SUPPLIER_ADDRESS= "UPDATE_SUPPLIER_ADDRESS"
export const  DELETE_SUPPLIER_ADDRESS = "DELETE_SUPPLIER_ADDRESS"



export const  GET_ALL_SUPPLIER = "GET_ALL_SUPPLIER"
export const  GET_ALL_SUPPLIER_CONTACT = "GET_ALL_SUPPLIER_CONTACT"
export const  GET_ALL_SUPPLIER_DELIVERY_LOCATION = "GET_ALL_SUPPLIER_DELIVERY_LOCATION"
export const  GET_ALL_SUPPLIER_CATEGORIES = "GET_ALL_SUPPLIER_CATEGORIES"
export const  GET_ALL_SUPPLIER_REASONS = "GET_ALL_SUPPLIER_REASONS"
export const  GET_SPECIFIED_SUPPLIER_DELIVERY_LOCATION = "GET_SPECIFIED_SUPPLIER_DELIVERY_LOCATION"
export const  GET_SPECIFIED_SUPPLIER_REASON = "GET_SPECIFIED_SUPPLIER_REASON"

export const  GET_SPECIFIED_SUPPLIER_CONTACT = "GET_SPECIFIED_SUPPLIER_CONTACT"
export const  GET_SPECIFIED_SUPPLIER = "GET_SPECIFIED_SUPPLIER"
export const  GET_SPECIFIED_SUPPLIER_CATEGORY = "GET_SPECIFIED_SUPPLIER_CATEGORY"

export const  UPDATE_SUPPLIER = "UPDATE_SUPPLIER"
export const  UPDATE_SUPPLIER_REASON = "UPDATE_SUPPLIER_REASON"

export const  UPDATE_SUPPLIER_CONTACT = "UPDATE_SUPPLIER_CONTACT"
export const  UPDATE_SUPPLIER_DELIVERY_LOCATION = "UPDATE_SUPPLIER_DELIVERY_LOCATION"
export const  UPDATE_DELIVERY_CATEGORY= "UPDATE_DELIVERY_CATEGORY"

export const  DELETE_SUPPLIER = "DELETE_SUPPLIER"
export const  DELETE_SUPPLIER_REASON = "DELETE_SUPPLIER_REASON"

export const  DELETE_SUPPLIER_DELIVERY_LOCATION = "DELETE_SUPPLIER_DELIVERY_LOCATION"
export const  DELETE_SUPPLIER_CONTACT = "DELETE_SUPPLIER_CONTACT"
export const  DELETE_SUPPLIER_CATEGORY = "DELETE_SUPPLIER_CATEGORY"

export const  REMOVE_SUPPLIER_REASON_FROM_ACTIVE_TO_INACTIVE = "REMOVE_SUPPLIER_REASON_FROM_ACTIVE_TO_INACTIVE"
export const  REMOVE_SUPPLIER_REASON_FROM_INACTIVE_TO_ACTIVE = "REMOVE_SUPPLIER_REASON_FROM_INACTIVE_TO_ACTIVE"
export const  ADD_ALL_SUPPLIER_REASON_FROM_INACTIVE_ACTIVE = "ADD_ALL_SUPPLIER_REASON_FROM_INACTIVE_ACTIVE"


    export const FETCH_SUPPLIER_ERROR="FETCH_SUPPLIER_ERROR"
    export const FETCH_SUPPLIER_LOADING="FETCH_SUPPLIER_LOADING"
    export const FETCH_SUPPLIER_SUCCESS="FETCH_SUPPLIER_SUCCESS"

    export const EDIT_SUPPLIER_ERROR="EDIT_SUPPLIER_ERROR"
    export const EDIT_SUPPLIER_SUCCESS="EDIT_SUPPLIER_SUCCESS"

    export const DELETE_SUPPLIER_ERROR="DELETE_SUPPLIER_ERROR"
    export const DELETE_SUPPLIER_SUCCESS="DELETE_SUPPLIER_SUCCESS"


  // SKU ACTION
export const  CREATE_SKU_ACTION = "CREATE_SKU_ACTION"
export const  UPDATE_SKU_ACTION = "UPDATE_SKU_ACTION"
export const  DELETE_SKU_ACTION = "DELETE_SKU_ACTION"
export const  GET_ALL_SKU_ACTION = "GET_ALL_SKU_ACTION"
export const GET_SPECIFIED_SKU_ACTION = "GET_SPECIFIED_SKU_ACTION"

  //page redirects action
export const PAGE_REDIRECT_ACTION = "PAGE_REDIRECT_ACTION"
export const SUB_PAGE_REDIRECT_ACTION = "SUB_PAGE_REDIRECT_ACTION"
export const SET_PAGE_NUMBER  = "SET_PAGE_NUMBER"
export const SET_SKU_PAGE_NUMBER ="SET_SKU_PAGE_NUMBER"

// category action
export const GET_ALL_PRODUCT_CATEGORIES_ACTION = "GET_ALL_PRODUCT_CATEGORIES_ACTION"

//sub category Action
export const GET_ALL_PRODUCT_SUB_CATEGORIES_ACTION = "GET_ALL_PRODUCT_SUB_CATEGORIES_ACTION"

// manufacture action
export const GET_ALL_MANUFACTURE_ACTON = "GET_ALL_MANUFACTURE_ACTON"

 //INPUT HANDLE
 export const  HANDLE_INPUT_DATA = "HANDLE_INPUT_DATA"
 export const HANDLE_TAG_INPUT_DATA = "HANDLE_TAG_INPUT_DATA"
 export const HANDLE_SKU_INPUT_DATA  = "HANDLE_SKU_INPUT_DATA"
 export const ERROR_HANDLE = "ERROR_HANDLE"

 
    // filter category Data
  export const FILTER_CATEGORY_DATA = "FILTER_CATEGORY_DATA"


//Plant Actions
export const CREATE_PLANT_ACTION = "CREATE_PLANT_ACTION"
export const UPDATE_PLANT_ACTION = "UPDATE_PLANT_ACTION"
export const DELETE_PLANT_ACTION = "DELETE_PLANT_ACTION"
export const GET_ALL_PLANT_ACTION = "GET_ALL_PLANT_ACTION"
export const GET_SPECIFIED_PLANT_ACTION ="GET_SPECIFIED_PLANT_ACTION"
export const DUPLICTE_PLANT ="DUPLICTE_PLANT"

// SKU ACTION
export const CREATE_PLANT_SKU_ACTION ="CREATE_PLANT_SKU_ACTION"
export const UPDATE_PLANT_SKU_ACTION ="UPDATE_PLANT_SKU_ACTION"
export const DELETE_PLANT_SKU_ACTION="DELETE_PLANT_SKU_ACTION"
export const GET_ALL_PLANT_SKU_ACTION="GET_ALL_PLANT_SKU_ACTION"
export const GET_PLANT_SPECIFIED_SKU_ACTION="GET_PLANT_SPECIFIED_SKU_ACTION"
export const UPDATE_SKU_ACTION_CLEAR = "UPDATE_SKU_ACTION_CLEAR"

//page redirects action

export const PAGE_PLANT_REDIRECT_ACTION="PAGE_PLANT_REDIRECT_ACTION"
export const SUB_PLANT_PAGE_REDIRECT_ACTION="SUB_PLANT_PAGE_REDIRECT_ACTION"

//INPUT HANDLE
export const HANDLE_PLANT_INPUT_DATA="HANDLE_PLANT_INPUT_DATA"
export const HANDLE_PLANT_TAG_INPUT_DATA="HANDLE_PLANT_TAG_INPUT_DATA"
export const HANDLE_PLANT_SKU_INPUT_DATA="HANDLE_PLANT_SKU_INPUT_DATA"

export const FILTER_GET_ALL_CATEGORY_DATA = "FILTER_GET_ALL_CATEGORY_DATA"
export const FILTER_GET_SLECTED_CATEGORY_DATA ="FILTER_GET_SLECTED_CATEGORY_DATA"
export const FILTER_GET_SLECTED_CATEGORY_SUB_DATA = "FILTER_GET_SLECTED_CATEGORY_SUB_DATA"
export const GET_ALL_PLANT_CATEGORIES = "GET_ALL_PLANT_CATEGORIES"


// Pagination of plant 
export const SET_PLANT_PAGE_NUMBER = "SET_PLANT_PAGE_NUMBER"
export const SET_PLANT_SKU_PAGE_NUMBER = "SET_PLANT_SKU_PAGE_NUMBER"


//get all attributes
export const GET_ALL_ATTRIBUtTES = "GET_ALL_ATTRIBUtTES"
export const CREATE_ALL_ATTRIBUTES="CREATE_ALL_ATTRIBUTES"
//search plant 
export const HANDLE_SEARCH_INPUT  = "HANDLE_SEARCH_INPUT"
export const HANDLE_RADIO_TOGGLE = " HANDLE_RADIO_TOGGLE"
export const HANDLE_CATEGORY_SEARCH = "HANDLE_CATEGORY_SEARCH"

//dashboard
export const GET_DASHBOARD_PAGE ="GET_DASHBOARD_PAGE"
export const SET_DASHBOARD_PAGE ="SET_DASHBOARD_PAGE"

//SIDEBAR PATH
export const GET_PATH = "GET_PATH" 
export const UPDATE_PATH = "UPDATE_PATH"

//user settings
export const GET_USERS_LIST = "GET_USERS_LIST"
export const ADD_USER = "ADD_USER"
export const SHOW_USER = "SHOW_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"
export const UPLOAD_USER_IMAGE = "UPLOAD_USER_IMAGE"
export const REMOVE_USER_IMAGE = "REMOVE_USER_IMAGE"

// User Access
export const GET_ROLES_LIST = "GET_ROLES_LIST"
export const SHOW_ROLE = "SHOW_ROLE"
export const UPDATE_ROLE = "UPDATE_ROLE"
export const DELETE_ROLE = "DELETE_ROLE"
export const ADD_ROLE  = "ADD_ROLE"
export const HANDLE_USER_ACCESS_INPUT_DATA = "HANDLE_USER_ACCESS_INPUT_DATA"
export const GET_PERMISSION_LIST = "GET_PERMISSION_LIST"
export const SHOW_SELECTED_USER = "SHOW_SELECTED_USER"
export const UPDATE_USER_PERMISSION = "UPDATE_USER_PERMISSION"

//organization setting
export const GET_ORGANIZATION_LIST ="GET_ORGANIZATION_LIST"
export const ADD_ORGANIZATION = "ADD_ORGANIZATION" 
export const SHOW_ORGANIZATION = "SHOW_ORGANIZATION" 
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION"
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION"
export const HANDLE_ORGANIZATION_INPUT_DATA = "HANDLE_ORGANIZATION_INPUT_DATA"
export const UPLOAD_ORGANIZATION_IMAGE = "UPLOAD_ORGANIZATION_IMAGE"
export const REMOVE_ORGANIZATION_IMAGE = "REMOVE_ORGANIZATION_IMAGE"


//customer settings
export const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const SHOW_CUSTOER = "SHOW_CUSTOER"
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"

export const qs = require('qs');
export const axios = require('axios');
export const AUTH_TOKEN = "1|Hk0h42DEoy9H0qPIMDdRzsh9JwrQjDbsHYX79Pf4"
axios.defaults.baseURL = 'https://zvky.flamingotech.ml';

export  const config = {
    headers: {
        "X-Tenant":"1602164a-25e4-4fac-bf64-57441cb52dce",
        "Content-type": "application/json",
        "Accept":"application/json",

         "Authorization": `Bearer ${AUTH_TOKEN}`,
    },
};




