
export const CHECK_LOGIN = "CHECK_LOGIN";
export const SIGN_IN_AUTH = "SIGN_IN_AUTH";


  //PRODUCT ACTION
export const  CREATE_PRODUCT_ACTION = "CREATE_PRODUCT_ACTION"
export const  UPDATE_PRODUCT_ACTION = "UPDATE_PRODUCT_ACTION"
export const  DELETE_PRODUCT_ACTION= "DELETE_PRODUCT_ACTION"
export const  GET_ALL_PRODUCT_ACTION= "GET_ALL_PRODUCT_ACTION"
export const  GET_SPECIFIED_PRODUCT_ACTION= "GET_SPECIFIED_PRODUCT_ACTION"
export const DUPLICTE_PRODUCT = "DUPLICTE_PRODUCT"

export const HANDLE_SEARCH_PINPUT  = "HANDLE_SEARCH_PINPUT"




//SUPPLIER ACTIONS
//SUPLIER CONTACTS CRUD
export const GET_SUPPLIER_LIST = "GET_SUPPLIER_LIST"
export const SET_SUPPLIER_PAGE_NUMBER = "SET_SUPPLIER_PAGE_NUMBER"
export const FILTER_SUPPLIER_DATA_BY_RADIO = "FILTER_SUPPLIER_DATA_BY_RADIO"
export const FILTER_SUPPLIER_BY_SEARCH = "FILTER_SUPPLIER_BY_SEARCH"
export const FILTER_SUPPLIER_BY_ALPHA = "constFILTER_SUPPLIER_BY_ALPHA"
export const ADD_SUPPLIER_ACCOUNTS = "ADD_SUPPLIER_ACCOUNTS"
export const GET_SUPPLIER_ACCOUNTS = "GET_SUPPLIER_ACCOUNTS"
export const ADD_SUPPLIER_CATEGORY = "ADD_SUPPLIER_CATEGORY"
export const GET_SUPPLIER_CATEGORY = "GET_SUPPLIER_CATEGORY"
export const ADD_SUPPLIER_LOCATION = "ADD_SUPPLIER_LOCATION"
export const GET_SUPPLIER_LOCATION = "GET_SUPPLIER_LOCATION"
export const GET_EXCHANGE_DATA = "GET_EXCHANGE_DATA"
export const GET_EXCHANGE_SUPPLIER_DATA = "GET_EXCHANGE_SUPPLIER_DATA"





export const  ADD_SUPPLIER_CONTACT_ERROR = "ADD_SUPPLIER_CONTACT_ERROR"
export const  ADD_SUPPLIER_CONTACT_LOADING = "ADD_SUPPLIER_CONTACT_LOADING"
export const  ADD_SUPPLIER_CONTACT_SUCCESS = "ADD_SUPPLIER_CONTACT_SUCCESS"

export const  DELETE_SUPPLIER_CONTACT_ERROR = "DELETE_SUPPLIER_CONTACT_ERROR"
export const  DELETE_SUPPLIER_CONTACT_LOADING = "DELETE_SUPPLIER_CONTACT_LOADING"
export const  DELETE_SUPPLIER_CONTACT_SUCCESS = "DELETE_SUPPLIER_CONTACT_SUCCESS"

export const  EDIT_SUPPLIER_CONTACT_ERROR = "EDIT_SUPPLIER_CONTACT_ERROR"
export const  EDIT_SUPPLIER_CONTACT_LOADING = "EDIT_SUPPLIER_CONTACT_LOADING"
export const  EDIT_SUPPLIER_CONTACT_SUCCESS = "EDIT_SUPPLIER_CONTACT_SUCCESS"

export const  FETCH_SUPPLIER_CONTACT_ERROR = "FETCH_SUPPLIER_CONTACT_ERROR"
export const  FETCH_SUPPLIER_CONTACT_LOADING = "FETCH_SUPPLIER_CONTACT_LOADING"
export const  FETCH_SUPPLIER_CONTACT_SUCCESS = "FETCH_SUPPLIER_CONTACT_SUCCESS"




export const  ADD_SUPPLIER = "ADD_SUPPLIER"
export const  ADD_SUPPLIER_DELIVERY_LOCATION = "ADD_SUPPLIER_DELIVERY_LOCATION"
export const  ADD_SUPPLIER_REASON = "ADD_SUPPLIER_REASON"


export const  CREATE_SUPPLIER_ADDRESS = "CREATE_SUPPLIER_ADDRESS"
// export const  GET_ALL_SUPPLIER_ADDRESS = "GET_ALL_SUPPLIER_ADDRESS"
export const  GET_SPECIFIED_SUPPLIER_ADDRESS = "GET_SPECIFIED_SUPPLIER_ADDRESS"
export const  UPDATE_SUPPLIER_ADDRESS= "UPDATE_SUPPLIER_ADDRESS"
export const  DELETE_SUPPLIER_ADDRESS = "DELETE_SUPPLIER_ADDRESS"
export const RESET_SUPPLIER_FILED ="RESET_SUPPLIER_FILED"

export const ADD_SUPPLIER_CONTACT = "ADD_SUPPLIER_CONTACT"
export const  GET_SUPPLIER_CONTACT ="GET_SUPPLIER_CONTACT"
export const GET_ALL_SUPPLIER_CONTACT= "GET_ALL_SUPPLIER_CONTACT"
export const DELETE_SUPPLIER_CONTACT = "DELETE_SUPPLIER_CONTACT"
export const UPDATE_SUPPLIER_CONTACT="UPDATE_SUPPLIER_CONTACT"


//supplier address
export const ADD_SUPPLIER_ADDRESS = "ADD_SUPPLIER_ADDRESS"
export const GET_SUPPLIER_ADDRESS = "GET_SUPPLIER_ADDRESS"
export const GET_ALL_SUPPLIER_ADDRESS= "GET_ALL_SUPPLIER_ADDRESS"
// export const DELETE_SUPPLIER_ADDRESS="DELETE_SUPPLIER_ADDRESS"
// export const UPDATE_SUPPLIER_ADDRESS= "UPDATE_SUPPLIER_ADDRESS"
export const RESET_SUPPLIER_CONTACT = "RESET_SUPPLIER_CONTACT"
export const DELETE_CUSTOMER_CONTACT = "DELETE_CUSTOMER_CONTACT"
export const HANDLE_INPUT_EXCHANGE1 = "HANDLE_INPUT_EXCHANGE1"
export const DELETE_CUSTOMER_ADDRESS = "DELETE_CUSTOMER_ADDRESS"



export const  GET_ALL_SUPPLIER = "GET_ALL_SUPPLIER"
// export const  GET_ALL_SUPPLIER_CONTACT = "GET_ALL_SUPPLIER_CONTACT"
export const  GET_ALL_SUPPLIER_DELIVERY_LOCATION = "GET_ALL_SUPPLIER_DELIVERY_LOCATION"
export const  GET_ALL_SUPPLIER_CATEGORIES = "GET_ALL_SUPPLIER_CATEGORIES"
export const  GET_ALL_SUPPLIER_REASONS = "GET_ALL_SUPPLIER_REASONS"
export const  GET_SPECIFIED_SUPPLIER_DELIVERY_LOCATION = "GET_SPECIFIED_SUPPLIER_DELIVERY_LOCATION"
export const  GET_SPECIFIED_SUPPLIER_REASON = "GET_SPECIFIED_SUPPLIER_REASON"

export const  GET_SPECIFIED_SUPPLIER_CONTACT = "GET_SPECIFIED_SUPPLIER_CONTACT"
export const  GET_SPECIFIED_SUPPLIER = "GET_SPECIFIED_SUPPLIER"
export const  GET_SPECIFIED_SUPPLIER_CATEGORY = "GET_SPECIFIED_SUPPLIER_CATEGORY"

export const  UPDATE_SUPPLIER = "UPDATE_SUPPLIER"
export const  UPDATE_SUPPLIER_REASON = "UPDATE_SUPPLIER_REASON"
export const  SHOW_SPECIFIC_SUPPLIER_REASON = "SHOW_SPECIFIC_SUPPLIER_REASON"
export const  HANDLE_REASON_INPUT_ACTION = "HANDLE_REASON_INPUT_ACTION"
export const  SHOW_SPECIFIC_SUPPLIER_CATEGORY = "SHOW_SPECIFIC_SUPPLIER_CATEGORY"
export const  UPDATE_SUPPLIER_CATEGORY = "UPDATE_SUPPLIER_CATEGORY"
export const  HANDLE_ZONE_INPUT_ACTION2 = "HANDLE_ZONE_INPUT_ACTION2"
export const  HANDLE_ZONE_INPUT_ACTION3 = "HANDLE_ZONE_INPUT_ACTION3"
export const  UPDATE_PLANT_SETTING_CATEGORY = "UPDATE_PLANT_SETTING_CATEGORY"
export const  SHOW_SPECIFIC_PLANT_SETTING_ATTRIBUTE = "SHOW_SPECIFIC_PLANT_SETTING_ATTRIBUTE"

export const  UPDATE_PRODUCT_SETTING_MANUFACTURES = "UPDATE_PRODUCT_SETTING_MANUFACTURES"
export const  SHOW_SPECIFIC_PRODUCT_SETTING_MANUFACTURES = "SHOW_SPECIFIC_PRODUCT_SETTING_MANUFACTURES"
export const FILTER_PLANT_MANAGER_INVENTORY_ACTION = "FILTER_PLANT_MANAGER_INVENTORY_ACTION"
export const FILTER_PRODUCT_MANAGER_INVENTORY_ACTION = "FILTER_PRODUCT_MANAGER_INVENTORY_ACTION"
export const RESET_PRODUCT_MANAGER_INVENTORY_ACTION = "RESET_PRODUCT_MANAGER_INVENTORY_ACTION"
//HANDLE_ZONE_INPUT_ACTION3

// export const  UPDATE_SUPPLIER_CONTACT = "UPDATE_SUPPLIER_CONTACT"
export const  UPDATE_SUPPLIER_DELIVERY_LOCATION = "UPDATE_SUPPLIER_DELIVERY_LOCATION"
export const  UPDATE_DELIVERY_CATEGORY= "UPDATE_DELIVERY_CATEGORY"

export const  DELETE_SUPPLIER = "DELETE_SUPPLIER"
export const  DELETE_SUPPLIER_REASON = "DELETE_SUPPLIER_REASON"

export const  DELETE_SUPPLIER_DELIVERY_LOCATION = "DELETE_SUPPLIER_DELIVERY_LOCATION"
// export const  DELETE_SUPPLIER_CONTACT = "DELETE_SUPPLIER_CONTACT"
export const  DELETE_SUPPLIER_CATEGORY = "DELETE_SUPPLIER_CATEGORY"


export const  REMOVE_SUPPLIER_REASON_FROM_ACTIVE_TO_INACTIVE = "REMOVE_SUPPLIER_REASON_FROM_ACTIVE_TO_INACTIVE"
export const  REMOVE_SUPPLIER_REASON_FROM_INACTIVE_TO_ACTIVE = "REMOVE_SUPPLIER_REASON_FROM_INACTIVE_TO_ACTIVE"
export const  ADD_ALL_SUPPLIER_REASON_FROM_INACTIVE_ACTIVE = "ADD_ALL_SUPPLIER_REASON_FROM_INACTIVE_ACTIVE"


    export const FETCH_SUPPLIER_ERROR="FETCH_SUPPLIER_ERROR"
    export const FETCH_SUPPLIER_LOADING="FETCH_SUPPLIER_LOADING"
    export const FETCH_SUPPLIER_SUCCESS="FETCH_SUPPLIER_SUCCESS"

    export const EDIT_SUPPLIER_ERROR="EDIT_SUPPLIER_ERROR"
    export const EDIT_SUPPLIER_SUCCESS="EDIT_SUPPLIER_SUCCESS"

    export const DELETE_SUPPLIER_ERROR="DELETE_SUPPLIER_ERROR"
    export const DELETE_SUPPLIER_SUCCESS="DELETE_SUPPLIER_SUCCESS"


  // SKU ACTION
export const  CREATE_SKU_ACTION = "CREATE_SKU_ACTION"
export const  UPDATE_SKU_ACTION = "UPDATE_SKU_ACTION"
export const  DELETE_SKU_ACTION = "DELETE_SKU_ACTION"
export const  GET_ALL_SKU_ACTION = "GET_ALL_SKU_ACTION"
export const GET_SPECIFIED_SKU_ACTION = "GET_SPECIFIED_SKU_ACTION"
export const CLEAR_SKU_FIELDS_PRODUCT = "CLEAR_SKU_FIELDS_PRODUCT"
export const CLEAR_SKU_FIELDS_PLANT = "CLEAR_SKU_FIELDS_PLANT"
export const CREATE_SKU_ACTION_AND_CLEAR = "CREATE_SKU_ACTION_AND_CLEAR"

  //page redirects action
export const PAGE_REDIRECT_ACTION = "PAGE_REDIRECT_ACTION"
export const SUB_PAGE_REDIRECT_ACTION = "SUB_PAGE_REDIRECT_ACTION"
export const SET_PAGE_NUMBER  = "SET_PAGE_NUMBER"
export const SET_SKU_PAGE_NUMBER ="SET_SKU_PAGE_NUMBER"

// category action
export const GET_ALL_PRODUCT_CATEGORIES_ACTION = "GET_ALL_PRODUCT_CATEGORIES_ACTION"

//sub category Action
export const GET_ALL_PRODUCT_SUB_CATEGORIES_ACTION = "GET_ALL_PRODUCT_SUB_CATEGORIES_ACTION"

// manufacture action
export const GET_ALL_MANUFACTURE_ACTON = "GET_ALL_MANUFACTURE_ACTON"

 //INPUT HANDLE
 export const  HANDLE_INPUT_DATA = "HANDLE_INPUT_DATA"
 export const HANDLE_TAG_INPUT_DATA = "HANDLE_TAG_INPUT_DATA"
 export const HANDLE_SKU_INPUT_DATA  = "HANDLE_SKU_INPUT_DATA"
 export const ERROR_HANDLE = "ERROR_HANDLE"

 
    // filter category Data
  export const FILTER_CATEGORY_DATA = "FILTER_CATEGORY_DATA"


//Plant Actions
export const CREATE_PLANT_ACTION = "CREATE_PLANT_ACTION"
export const UPDATE_PLANT_ACTION = "UPDATE_PLANT_ACTION"
export const DELETE_PLANT_ACTION = "DELETE_PLANT_ACTION"
export const GET_ALL_PLANT_ACTION = "GET_ALL_PLANT_ACTION"
export const GET_SPECIFIED_PLANT_ACTION ="GET_SPECIFIED_PLANT_ACTION"
export const DUPLICTE_PLANT ="DUPLICTE_PLANT"


// SKU ACTION
export const CREATE_PLANT_SKU_ACTION ="CREATE_PLANT_SKU_ACTION"
export const UPDATE_PLANT_SKU_ACTION ="UPDATE_PLANT_SKU_ACTION"
export const DELETE_PLANT_SKU_ACTION="DELETE_PLANT_SKU_ACTION"
export const GET_ALL_PLANT_SKU_ACTION="GET_ALL_PLANT_SKU_ACTION"
export const GET_PLANT_SPECIFIED_SKU_ACTION="GET_PLANT_SPECIFIED_SKU_ACTION"
export const UPDATE_SKU_ACTION_CLEAR = "UPDATE_SKU_ACTION_CLEAR"
export const GET_SKU_SPECIFIED_PRODUCT = "GET_SKU_SPECIFIED_PRODUCT"
export const GET_SINGLE_PLANT_SKU = "GET_SINGLE_PLANT_SKU"

//page redirects action

export const PAGE_PLANT_REDIRECT_ACTION="PAGE_PLANT_REDIRECT_ACTION"
export const SUB_PLANT_PAGE_REDIRECT_ACTION="SUB_PLANT_PAGE_REDIRECT_ACTION"

//INPUT HANDLE
export const HANDLE_PLANT_INPUT_DATA="HANDLE_PLANT_INPUT_DATA"
export const HANDLE_PLANT_TAG_INPUT_DATA="HANDLE_PLANT_TAG_INPUT_DATA"
export const HANDLE_PLANT_SKU_INPUT_DATA="HANDLE_PLANT_SKU_INPUT_DATA"

export const FILTER_GET_ALL_CATEGORY_DATA = "FILTER_GET_ALL_CATEGORY_DATA"
export const FILTER_GET_SLECTED_CATEGORY_DATA ="FILTER_GET_SLECTED_CATEGORY_DATA"
export const FILTER_GET_SLECTED_CATEGORY_SUB_DATA = "FILTER_GET_SLECTED_CATEGORY_SUB_DATA"
export const GET_ALL_PLANT_CATEGORIES = "GET_ALL_PLANT_CATEGORIES"
export const HANDLE_CATEGORY_INPUT_DATA = "HANDLE_CATEGORY_INPUT_DATA"
export const HANDLE_ADD_PLANT_CATEGORY = "HANDLE_ADD_PLANT_CATEGORY"
export const HANDLE_DRAG_PLANT_CATEGORY = "HANDLE_DRAG_PLANT_CATEGORY"
export const HANDLE_DRAG_CATEGORY_SORT = "HANDLE_DRAG_CATEGORY_SORT"
export const HANDLE_CATEGORY_DELETE = "HANDLE_CATEGORY_DELETE"
export const HANDLE_MANUFACTURE_DATA = "HANDLE_MANUFACTURE_DATA"
export const HANDLE_SELECTED_CATEGORY = "HANDLE_SELECTED_CATEGORY"





// Pagination of plant 
export const SET_PLANT_PAGE_NUMBER = "SET_PLANT_PAGE_NUMBER"
export const SET_PLANT_SKU_PAGE_NUMBER = "SET_PLANT_SKU_PAGE_NUMBER"


//get all attributes
export const GET_ALL_ATTRIBUtTES = "GET_ALL_ATTRIBUtTES"
export const CREATE_ALL_ATTRIBUTES="CREATE_ALL_ATTRIBUTES"
export const GET_ALL_SUB_ATTRIBUtTES = "GET_ALL_SUB_ATTRIBUtTES"
export const HANDLE_DRAG_ATTRIBUTE_CATEGORY = "HANDLE_DRAG_ATTRIBUTE_CATEGORY"
export const HANDLE_DRAG_ATTRIBUTE_SORT = "HANDLE_DRAG_ATTRIBUTE_SORT"
export const HANDLE_DELETE_ATTRIBUTE = "HANDLE_DELETE_ATTRIBUTE"
export const HANDLE_ZONE_INPUT_ACTION = "HANDLE_ZONE_INPUT_ACTION"
export const HANDLE_ADD_ZONE_ATTRIBUTE = "HANDLE_ADD_ZONE_ATTRIBUTE"
export const HANDLE_POSITION_INPUT_ACTION = "HANDLE_POSITION_INPUT_ACTION"
export const HANDLE_ADD_POSITION_ATTRIBUTE = "HANDLE_ADD_POSITION_ATTRIBUTE"
export const HANDLE_CLEAR_SUB_ATTRIBUTE_VALUE = "HANDLE_CLEAR_SUB_ATTRIBUTE_VALUE"
//search plant 
export const HANDLE_SEARCH_INPUT  = "HANDLE_SEARCH_INPUT"
export const HANDLE_RADIO_TOGGLE = " HANDLE_RADIO_TOGGLE"
export const HANDLE_CATEGORY_SEARCH = "HANDLE_CATEGORY_SEARCH"
//search Product 
export const HANDLE_PRODUCT_SEARCH_INPUT="HANDLE_PRODUCT_SEARCH_INPUT"
export const HANDLE_PRODUCT_RADIO_TOGGLE="HANDLE_PRODUCT_RADIO_TOGGLE"
//update attributeSHOW_SUB_ATTRIBUtTES
export const HANDLE_UPDATE_ATTRIBUTE="HANDLE_UPDATE_ATTRIBUTE"
export const SHOW_SUB_ATTRIBUTE="SHOW_SUB_ATTRIBUTE"
export const HANDLE_UPDATE_SUB_ATTRIBUTE="HANDLE_UPDATE_SUB_ATTRIBUTE"

export const UPDATE_CHECK_BOX = "UPDATE_CHECK_BOX"
export const CHECK_BOX = "CHECK_BOX"
//dashboard
export const GET_DASHBOARD_PAGE ="GET_DASHBOARD_PAGE"
export const SET_DASHBOARD_PAGE ="SET_DASHBOARD_PAGE"
export const HANDLE_INPUT_CUSTOMER = "HANDLE_INPUT_CUSTOMER"

//SIDEBAR PATH
export const GET_PATH = "GET_PATH" 
export const UPDATE_PATH = "UPDATE_PATH"

//user settings
export const GET_USERS_LIST = "GET_USERS_LIST"
export const ADD_USER = "ADD_USER"
export const SHOW_USER = "SHOW_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"
export const UPLOAD_USER_IMAGE = "UPLOAD_USER_IMAGE"
export const REMOVE_USER_IMAGE = "REMOVE_USER_IMAGE"

// User Access
export const GET_ROLES_LIST = "GET_ROLES_LIST"
export const SHOW_ROLE = "SHOW_ROLE"
export const UPDATE_ROLE = "UPDATE_ROLE"
export const DELETE_ROLE = "DELETE_ROLE"
export const ADD_ROLE  = "ADD_ROLE"
export const HANDLE_USER_ACCESS_INPUT_DATA = "HANDLE_USER_ACCESS_INPUT_DATA"
export const GET_PERMISSION_LIST = "GET_PERMISSION_LIST"
export const SHOW_SELECTED_USER = "SHOW_SELECTED_USER"
export const UPDATE_USER_PERMISSION = "UPDATE_USER_PERMISSION"

//organization setting
export const GET_ORGANIZATION_LIST ="GET_ORGANIZATION_LIST"
export const ADD_ORGANIZATION = "ADD_ORGANIZATION" 
export const SHOW_ORGANIZATION = "SHOW_ORGANIZATION" 
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION"
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION"
export const HANDLE_ORGANIZATION_INPUT_DATA = "HANDLE_ORGANIZATION_INPUT_DATA"
export const UPLOAD_ORGANIZATION_IMAGE = "UPLOAD_ORGANIZATION_IMAGE"
export const REMOVE_ORGANIZATION_IMAGE = "REMOVE_ORGANIZATION_IMAGE"

//Inventory manage system
export const GET_LOCATION_LIST = "GET_LOCATION_LIST"
export const GET_PLANT_CATEGORY_LIST = "GET_PLANT_CATEGORY_LIST"
export const GET_PRODUCT_CATEGORY_LIST = "GET_PRODUCT_CATEGORY_LIST"
export const GET_ALL_PLANT_INVENTORY_ACTION ="GET_ALL_PLANT_INVENTORY_ACTION"
export const PLANT_INVENTORY_FILTER = "PLANT_INVENTORY_FILTER"
export const GET_ALL_PRODUCT_INVENTORY_ACTION = "GET_ALL_PRODUCT_INVENTORY_ACTION"
export const PRODUCT_INVENTORY_FILTER = "PRODUCT_INVENTORY_FILTER"
export const GET_MANUFACTURER_CATEGORY_LIST = "GET_MANUFACTURER_CATEGORY_LIST"
export const GET_ALL_PLANTMANAGER_INVENTORY_ACTION = "GET_ALL_PLANTMANAGER_INVENTORY_ACTION"
export const GET_ALL_PRODUCTMANAGER_INVENTORY_ACTION = "GET_ALL_PRODUCTMANAGER_INVENTORY_ACTION"
export const GET_ALL_PRODUCT_INVENTORY_ACTION_SKU = "GET_ALL_PRODUCT_INVENTORY_ACTION_SKU"

export const GET_PLANT_DATA = "GET_PLANT_DATA"

//customer settings
export const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const SHOW_CUSTOER = "SHOW_CUSTOER"
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"
export const HANDLE_ALL_FILTER = "HANDLE_ALL_FILTER"
export const  FILTER_DATA_BY_RADIO = "FILTER_DATA_BY_RADIO"
export const FILTER_DATA_BY_SEARCH ="FILTER_DATA_BY_SEARCH"
export const FILTER_DATA_BY_ALPHA = "FILTER_DATA_BY_ALPHA"
export const HANLE_DATA_CHANGE = "HANLE_DATA_CHANGE"
export const HANDLE_INPUT = "HANDLE_INPUT"
export const ADD_NOTIFICATION  = "ADD_NOTIFICATION"
export const GET_CUSTOMER_NOTIFICATION = "GET_CUSTOMER_NOTIFICATION"
export const ADD_EMAIL  = "ADD_EMAIL"
export const GET_EMAIL_NOTIFICATION = "GET_EMAIL_NOTIFICATION"
export const HANDLE_INPUT_EXCHANGE = "HANDLE_INPUT_EXCHANGE"
export const ADD_FINANCES_DATA = "ADD_FINANCES_DATA"
export const ADD_FINANCES_SUPPLIER_DATA = "ADD_FINANCES_SUPPLIER_DATA"
export const HANDLE_SUPPLIER_INPUT_EXCHANGE  = "HANDLE_SUPPLIER_INPUT_EXCHANGE"
export const ADD_INTEREST_DATA = "ADD_INTEREST_DATA"
export const ADD_PRINT_DATA = "ADD_PRINT_DATA"
export const ADD_CUSTOMER_TYPE = "ADD_CUSTOMER_TYPE"
export const GET_ALL_CUSTOMER_TYPES = "GET_ALL_CUSTOMER_TYPES"
export const HANDLE_DRAG_CUSTOMER_CATEGORY  ="HANDLE_DRAG_CUSTOMER_CATEGORY"
export const GET_CUSTOMER_DELIVERY_LIST = "GET_CUSTOMER_DELIVERY_LIST"
export const ADD_CUSTOMER_DELIVERY = "ADD_CUSTOMER_DELIVERY"
export const GET_CUSTOMER_STATUS  = "GET_CUSTOMER_STATUS"
export const ADD_CUSTOMER_STATUS = "ADD_CUSTOMER_STATUS"
export const  ADD_CUSTOMER_REASON = "ADD_CUSTOMER_REASON"
export const  GET_CUSTOMER_REASON = "GET_CUSTOMER_REASON"
export const GET_CUSTOMER_TERMS ="GET_CUSTOMER_TERMS"
export const ADD_CUSTOMER_TERMS ="ADD_CUSTOMER_TERMS"
export const  ADD_CUSTOMER_RETURN_REASON = "ADD_CUSTOMER_RETURN_REASON"
export const GET_CUSTOMER_RETURN_REASON = "GET_CUSTOMER_RETURN_REASON"
export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER"
export const EDIT_CUSTOMER = "EDIT_CUSTOMER"
export const TYPE_OF_ACTION = "TYPE_OF_ACTION"
export const GET_CUSTOMER_BY_ID = "GET_CUSTOMER_BY_ID"
export const RESET_CUSTOMER_FILEDS = "RESET_CUSTOMER_FILEDS"
export const GET_INTEREST_DATA  = "GET_INTEREST_DATA"
export const GET_PRINT_DATA = "GET_PRINT_DATA"
export const ADD_CUSTOMER_CONTACT = "ADD_CUSTOMER_CONTACT"
export const GET_CUSTOMER_CONTACTS_LIST = "GET_CUSTOMER_CONTACTS_LIST"
export const UPDATE_CUSTOMER_CONTACT = "UPDATE_CUSTOMER_CONTACT"
export const GET_CUSTOMER_CONTACT_BY_ID = "GET_CUSTOMER_CONTACT_BY_ID"
export const RE_SET_ADDRESS_FILED ="RE_SET_ADDRESS_FILED"
export const RESET_CONTACT = "RESET_CONTACT"
export const TYPE_OF_SUPPLIER_ACTION = "TYPE_OF_SUPPLIER_ACTION"
export const GET_SUPPLIER_BY_ID = "GET_SUPPLIER_BY_ID"

export const SHOW_SPECIFIC_CUSTOMER_TYPE_SETTING = "SHOW_SPECIFIC_CUSTOMER_TYPE_SETTING"
export const UPDATE_CUSTOMER_TYPE_SETTING = "UPDATE_CUSTOMER_TYPE_SETTING"
export const HANDLE_CUSTOMER_SETTIING_INPUT_DATA = "HANDLE_CUSTOMER_SETTIING_INPUT_DATA"
export const UPDATE_CUSTOMER_DELIVERY_METHOD_SETTING = "UPDATE_CUSTOMER_DELIVERY_METHOD_SETTING"
export const SHOW_SPECIFIC_CUSTOMER_DELIVERY_METHOD_SETTING = "SHOW_SPECIFIC_CUSTOMER_DELIVERY_METHOD_SETTING"

//address  UPDATE_CUSTOMER_DELIVERY_METHOD_SETTING
export const ADD_CONTACT_ADDRESS = "ADD_CONTACT_ADDRESS"
export const GET_CONTACT_ADDRESSES = "GET_CONTACT_ADDRESSES"
export const UPDATE_CONTACT_ADDRESS = "UPDATE_CONTACT_ADDRESS"
export const GET_CONTACT_ADDRESSES_BY_CONTACTID = "GET_CONTACT_ADDRESSES_BY_CONTACTID"
//RESET_USERDATA
export const RESET_USERDATA = "RESET_USERDATA"
//RESET_SUPPLIER_DATA
export const RESET_SUPPLIER_DATA = "RESET_SUPPLIER_DATA"

//DATA_CHANGES_ALERT
export const DATA_CHANGES_ALERT = "DATA_CHANGES_ALERT"

export const UPDATE_CUSTOMER_STATUS_LEVEL_SETTING = "UPDATE_CUSTOMER_STATUS_LEVEL_SETTING"
export const SHOW_SPECIFIC_CUSTOMER_STATUS_LEVEL_SETTING = "SHOW_SPECIFIC_CUSTOMER_STATUS_LEVEL_SETTING"


export const UPDATE_CUSTOMER_RETURN_REASON_SETTING = "UPDATE_CUSTOMER_RETURN_REASON_SETTING"
export const SHOW_SPECIFIC_CUSTOMER_RETURN_REASON_SETTING = "SHOW_SPECIFIC_CUSTOMER_RETURN_REASON_SETTING"


export const UPDATE_CUSTOMER_ACCOUNT_REASON_SETTING = "UPDATE_CUSTOMER_ACCOUNT_REASON_SETTING"
export const SHOW_SPECIFIC_CUSTOMER_ACCOUNT_REASON_SETTING = "SHOW_SPECIFIC_CUSTOMER_ACCOUNT_REASON_SETTING"


export const UPDATE_CUSTOMER_TERMS_SETTING = "UPDATE_CUSTOMER_TERMS_SETTING"
export const SHOW_SPECIFIC_CUSTOMER_TERMS_SETTING = "SHOW_SPECIFIC_CUSTOMER_TERMS_SETTING"










//PURCHASE ORDER  SET_PAGE_NUMBER_PO
export const  FILTER_DATA_BY_ALPHABETIC_PO = "FILTER_DATA_BY_ALPHABETIC_PO"
export const  FILTER_DATA_BY_SEARCH_SN_PO = "FILTER_DATA_BY_SEARCH_SN_PO"
export const  SET_PAGE_NUMBER_PO = "SET_PAGE_NUMBER_PO"

//Product Manufacture Settings
export const GET_ALL_PRODUCT_MANUFACTURES = "GET_ALL_PRODUCT_MANUFACTURES"
export const HANDLE_PRODUCT_MANUFACTURE_INPUT_DATA = "HANDLE_PRODUCT_MANUFACTURE_INPUT_DATA"
export const HANDLE_ADD_PRODUCT_MANUFACTURE = "HANDLE_ADD_PRODUCT_MANUFACTURE"
export const HANDLE_DRAG_PRODUCT_MANUFACTURE = "HANDLE_DRAG_PRODUCT_MANUFACTURE"
export const HANDLE_DRAG_MANUFACTURER_SORT = "HANDLE_DRAG_MANUFACTURER_SORT"
export const HANDLE_PRODUCT_MANUFACTURE_DELETE = "HANDLE_PRODUCT_MANUFACTURE_DELETE"

export const SHOW_LOCATION_TYPE_SUB_ATTRIBUTE = "SHOW_LOCATION_TYPE_SUB_ATTRIBUTE"

export const qs = require('qs');
export const axios = require('axios');
export const AUTH_TOKEN = "1|Hk0h42DEoy9H0qPIMDdRzsh9JwrQjDbsHYX79Pf4"
axios.defaults.baseURL = 'https://zvky.flamingotech.ml';

export  const config = {
    headers: {
        "X-Tenant":"1602164a-25e4-4fac-bf64-57441cb52dce",
        "Content-type": "application/json",
        "Accept":"application/json",

         "Authorization": `Bearer ${AUTH_TOKEN}`,
    },
};




